"""
Django settings for PromptManager project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os.path
from pathlib import Path
from .base import *

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


db_path = BASE_DIR / "pmctl/db.sqlite3" if os.getenv('SQLITE_DB_PATH') == None else os.getenv('SQLITE_DB_PATH')

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": db_path,
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, "prompt.log"),
            # 'filename': '/var/log/promptmanager/backend/prompt.log',
        },
    },
    'loggers': {
        # 'django': {
        #     'handlers': ['file'],
        #     'level': 'DEBUG',
        #     'propagate': True,
        # },
        'pm_log':{
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}
